CREATE TABLE "credential_profiles" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"snmp_version" text NOT NULL,
	"community_string" text,
	"snmp_v3_username" text,
	"snmp_v3_auth_protocol" text,
	"snmp_v3_auth_password" text,
	"snmp_v3_priv_protocol" text,
	"snmp_v3_priv_password" text,
	"snmp_v3_security_level" text,
	"is_default" boolean DEFAULT false,
	"priority" integer DEFAULT 0,
	"is_active" boolean DEFAULT true,
	"tenant_id" varchar NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "discovered_devices" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"job_id" varchar NOT NULL,
	"ip_address" text NOT NULL,
	"mac_address" text,
	"hostname" text,
	"sys_name" text,
	"sys_descr" text,
	"sys_object_id" text,
	"serial_number" text,
	"manufacturer" text,
	"model" text,
	"interfaces" jsonb,
	"os_name" text,
	"os_version" text,
	"discovery_method" text NOT NULL,
	"status" text DEFAULT 'discovered' NOT NULL,
	"credential_profile_id" varchar,
	"open_ports" jsonb,
	"port_fingerprint" text,
	"mac_oui" text,
	"is_duplicate" boolean DEFAULT false,
	"duplicate_asset_id" varchar,
	"duplicate_match_field" text,
	"is_imported" boolean DEFAULT false,
	"imported_at" timestamp,
	"imported_asset_id" varchar,
	"site_id" varchar,
	"site_name" text,
	"raw_data" jsonb,
	"notes" text,
	"tenant_id" varchar NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "discovery_jobs" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"job_id" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"initiated_by" varchar NOT NULL,
	"initiated_by_name" text NOT NULL,
	"os_type" text NOT NULL,
	"site_id" varchar,
	"site_name" text,
	"network_range" text,
	"total_hosts" integer DEFAULT 0,
	"scanned_hosts" integer DEFAULT 0,
	"successful_hosts" integer DEFAULT 0,
	"partial_hosts" integer DEFAULT 0,
	"unreachable_hosts" integer DEFAULT 0,
	"results" jsonb,
	"error_log" text,
	"started_at" timestamp,
	"completed_at" timestamp,
	"expires_at" timestamp NOT NULL,
	"tenant_id" varchar NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "discovery_jobs_job_id_unique" UNIQUE("job_id")
);
--> statement-breakpoint
CREATE TABLE "discovery_tokens" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"token" text NOT NULL,
	"job_id" varchar NOT NULL,
	"tenant_id" varchar NOT NULL,
	"site_id" varchar,
	"is_used" boolean DEFAULT false,
	"used_at" timestamp,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "discovery_tokens_token_unique" UNIQUE("token")
);
